"""crear tabla emails

Revision ID: 267de776ba38
Revises: 
Create Date: 2026-08-05 13:03:57.891363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267de776ba38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.Enum('IMPORTANTE', 'NEWSLETTER', 'SPAM', 'SIN_CLASIFICAR', name='emailcategory'), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('first_seen_unread_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moved_to_pending', sa.Boolean(), nullable=True),
    sa.Column('processed_by_ai', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_gmail_message_id'), 'emails', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_emails_gmail_thread_id'), 'emails', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_emails_id'), 'emails', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_gmail_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_gmail_message_id'), table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
